### ISSUE TITLE
[BUG] Client crashing on world startup

### ISSUE THREAD

**Issue by Atlamil** [Ridderrasmus/RPVoiceChat#127]
**Describe the bug**
Testing out a group of mods in single player to verify they work together, narrowed it down to these 2

**OS**
Windows

**Mod version**
2.3.8

**Game version**
1.19.3

**If using other mods, which?**
Translocator Engineering Redux v1.4.9

**To Reproduce**
I went through the RP Voice Chat setup prior to this
1. Create world with default settings
2. Client crashes near the end of world loading

**Additional context**
Relevant exception:
Exception: Attempted to read past the end of the stream.
   at ProtoBuf.ProtoReader.ReadUInt64Variant() in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 463
   at ProtoBuf.ProtoReader.SkipField() in C:\Code\pb-net_24\src\protobuf-net\ProtoReader.cs:line 785
   at proto_38(Object, ProtoReader)
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p)
   at Vintagestory.Client.NoObf.NetworkChannel.OnPacket(Packet_CustomPacket p)
   at RPVoiceChat.Networking.NativeNetworkClient.ProcessInBackground(Int32 channelId, Packet_CustomPacket customPacket)
   at RPVoiceChat.SystemNetworkProcessPatch.ProcessInBackground(Boolean& __result, Packet_Server packet)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.ProcessInBackground_Patch1(SystemNetworkProcess this, Packet_Server packet)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.TryReadPacket(Byte[] data, Int32 dataLength)
   at Vintagestory.Client.NoObf.SystemNetworkProcess.NetworkProcess()
   at Vintagestory.Client.NoObf.ClientThread.Update()
   at Vintagestory.Client.NoObf.ClientThread.Process()

**Any logs should also be attached**
[client-main.txt](https://github.com/Ridderrasmus/RPVoiceChat/files/14088312/client-main.txt)

**Comment by Ridderrasmus** [comment]
Had a quick look at this. As far as I can tell no functionality breaks between the two mods in spite of the crash.
Temporary workaround while I track the source of the problem down properly is to create your world without one of either RPVoiceChat or Translocator Engineering Redux first and then afterwards enabling it again.

Very much appreciate the helpful bug report!
