### ISSUE TITLE
Error getting source SourceState logged rapidly

### ISSUE THREAD

**Issue by flintvint** [Ridderrasmus/RPVoiceChat#129]
**Describe the bug**
The game crashed and `client-debug.txt` is seen generating around 250 log entries per second with `[Debug] [RPVoiceChat] Error getting source SourceState` during and after the crash, when the game has closed down, and the crash report is held open. There were 45k lines of this in the log up to the crash and 105k after closing out the dialog window.

Game Version: v1.19.3 (Stable)
`3/10/2024 12:40:27 AM: Critical error occurred`

**OS**
Windows 10

**Mod version**
v2.3.8

**Game version**
v1.19.3

**If using other mods, which?**
Loaded Mods: aculinaryartillery@1.1.2, bettercrates@1.7.0, blacksmithname@1.1.6, chiseltools@1.10.4, craftablecompanion@1.0.0, millwright@1.1.4, moreicons@1.1.0, nooffhand@1.0.1, pieontheshelf@1.0.0, potontheshelf@1.0.0, primitivesurvival@3.4.7, repairablelocust@1.2.0, rpvoicechat@2.3.8, ssppvv@1.0.5, upgradeablelocust@1.0.1, game@1.19.3, zoombuttonreborn@1.6.0, alchemy@1.6.25, animalcages@3.0.2, betterbloomeriesreborn@1.0.5, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.3, blacksmithenhancements@1.0.4, butchering@1.5.2, carryon@1.7.4, coinage@1.10.1, commonlib@2.3.2, divisionoflabor@1.0.8, expandedfoods@1.6.8, fairplayguardian@1.1.7, fancyplanters@1.2.0, glowingprojectiles@1.1.3, herbarium@1.0.5, sailboat@1.2.8, loreweapons@1.0.1, meteoricexpansion@1.2.5, moreanimals@1.3.3, nohands@0.1.1, prospecttogether@1.3.0, scarecrow@1.4.3, simpleemotemenu@1.1.0, spawnhighlight@1.1.0, statushud@1.4.3, stonebakeoven@1.1.3, stonerailings@1.2.0, targetDotSmall@1.1.0, vinconomy@0.2.3, creative@1.19.3, survival@1.19.3, waypointcolours@1.1.1, wildfarmingrevival@1.1.8, em@2.5.0, extraoverlays@1.3.1, playercorpse@1.9.0, rifteye@0.3.4, simplewinddirection@1.0.2, stonequarry@3.2.1, vinterra@1.0.11, vsradiomod@0.2.0, wildcraftfruit@1.1.0, wildcraftherb@0.0.0, wildcrafttree@1.0.0, bricklayers@2.5.0

**To Reproduce**
Unknown

**Expected behavior**
A rate limit of this or some timeout to give up and try later?

**Screenshots**

**Additional context**
Was not using voice, but potentially getting within range of another player.

**Any logs should also be attached**

Other OpenAL issues show up. Dates change as midnight is crossed.

```
9.3.2024 21:28:57.018 [VerboseDebug] [RPVoiceChat] [Internal] Failed to open capture device: InvalidValue, Default, 48000, MultiQuad16Ext, 24000
9.3.2024 21:28:57 [Debug] [RPVoiceChat] Succesfully created an audio capture device with arguments: Default, 48000, Stereo16, 24000

9.3.2024 23:13:18.304 [VerboseDebug] [Notification] [RPVoiceChat] Attempting to connect with UDP client
9.3.2024 23:13:18.304 [VerboseDebug] [Notification] [RPVoiceChat] Server doesn't support UDP transport, aborting
9.3.2024 23:13:18.304 [VerboseDebug] [Notification] [RPVoiceChat] Attempting to connect with CustomTCP client
9.3.2024 23:13:18.304 [VerboseDebug] [Notification] [RPVoiceChat] Server doesn't support CustomTCP transport, aborting
9.3.2024 23:13:18.304 [VerboseDebug] [Notification] [RPVoiceChat] Attempting to connect with NativeTCP client
9.3.2024 23:13:18.304 [VerboseDebug] [Notification] [RPVoiceChat] Successfully connected with the NativeTCP client

10.3.2024 00:40:25 [Warning] OpenAL Error during setvolume(val) of sound game:sounds/environment/waterwaves.ogg: IllegalCommand
10.3.2024 00:40:25 [Warning] OpenAL Error during setvolume(val) of sound game:sounds/environment/rainwindow.ogg: IllegalCommand

10.3.2024 00:40:25 [Debug] [RPVoiceChat] Error getting source SourceState 
10.3.2024 00:40:25 [Debug] [RPVoiceChat] Error getting source SourceState 
10.3.2024 00:40:25 [Debug] [RPVoiceChat] Error getting source SourceState 
... 250/sec
```

**Comment by flintvint** [comment]
A third player in game kept approaching me and another player and repeatedly crashes within the voice chat radius. Here is their log:

```
10.3.2024 08:14:52 [Fatal] Caught unhandled exception in thread 'networkproc'. Exiting game.
10.3.2024 08:14:52 [Error] Exception: This OpenAL function could not be loaded. This likely means that this extension isn't present in the current context.
   at OpenAL_AL_Extension_Null_GetProcAddress_Exception_Delegate_58cde30c-6442-4a5b-bc74-bf6326b3477e(Int32, Int32&)
   at OpenTK.Audio.OpenAL.ALC.EFX.GenFilters(Int32 count, Int32& filters)
   at OpenTK.Audio.OpenAL.ALC.EFX.GenFilter()
   at RPVoiceChat.Audio.Effects.FilterLowpass..ctor(Int32 source) in D:\VintageStoryModding\VSModding\RPVoiceChat\RPVoiceChat\src\Audio\Effects\Filters\FilterLowpass.cs:line 17
   at RPVoiceChat.Audio.PlayerAudioSource.UpdatePlayer() in D:\VintageStoryModding\VSModding\RPVoiceChat\RPVoiceChat\src\Audio\Output\PlayerAudioSource.cs:line 107
   at RPVoiceChat.Audio.AudioOutputManager.HandleAudioPacket(AudioPacket packet, PlayerAudioSource source) in D:\VintageStoryModding\VSModding\RPVoiceChat\RPVoiceChat\src\Audio\Output\AudioOutputManager.cs:line 84
   at RPVoiceChat.Audio.AudioOutputManager.HandleAudioPacket(AudioPacket packet) in D:\VintageStoryModding\VSModding\RPVoiceChat\RPVoiceChat\src\Audio\Output\AudioOutputManager.cs:line 72
   at RPVoiceChat.RPVoiceChatClient.OnAudioReceived(AudioPacket packet) in D:\VintageStoryModding\VSModding\RPVoiceChat\RPVoiceChat\src\RPVoiceChatClient.cs:line 122
   at RPVoiceChat.Client.PlayerNetworkClient.AudioPacketReceived(AudioPacket packet) in D:\VintageStoryModding\VSModding\RPVoiceChat\RPVoiceChat\src\Client\PlayerNetworkClient.cs:line 112
   ```

**Comment by RomainOdeval** [comment]
> A third player in game kept approaching me and another player and repeatedly crashes within the voice chat radius. Here is their log

Sorry, i know it's a bit "late" but some fixes have been pushed last 6 months.
With those fixes, did you have this specific errors again ?

Thank you

**Comment by RomainOdeval** [comment]
No answer, nearly one-year problem, i close it.
Feel free to redo an issue if a similar problem still persist.
Thank you for your understanding.
