### ISSUE TITLE
[BUG] Client Crash on Server Join with newest 1.18.14 game update and RPVoiceChat 2.1.0

### ISSUE THREAD

**Issue by TrundleThaGreat** [Ridderrasmus/RPVoiceChat#84]
**Describe the bug**
Client Crashes when connecting to server after new 1.18.14 update.

**OS**
Windows 10

**Mod version**
v2.1.0

**Game version**
v1.18.14

**If using other mods, which?**
None

**To Reproduce**
1. Download Mod
2. Add mod to server side
3. Have Client connect to server
4. Crash Report opens and frozen at "Client Connecting" screen.

**Expected behavior**
Connect to the server and use voice chat

**Screenshots**

**Additional context**
This is the only mod on the server.

**Any logs should also be attached**
Running on 64 bit Windows with 32677 MB RAM
Game Version: v1.18.14 (Stable)
10/3/2023 1:00:21 PM: Critical error occurred
Loaded Mods: game@1.18.14, creative@1.18.14, survival@1.18.14
System.Exception: Don't know how to instantiate item of class 'soundemittingitem' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 580
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 392
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 334
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Dmitry221060** [comment]
Status update: I was able to confirm and reproduce the issue, working on a fix right now 👍

**Comment by Dmitry221060** [comment]
Status update: I've identified the issue and made a fix. I'll run few additional quick checks to make sure nothing else broke and we will upload new version of the mod

**Comment by Dmitry221060** [comment]
@TrundleThaGreat @RogueRaiden 
We've released 2.2.0 which should fix this issue. (It also adds player list into the mod menu so you can adjust volume of individual players)

**Comment by Dmitry221060** [comment]
Status update: The issue is persistent on Linux and is caused by the change in the way game loads code libraries. A proper fix will take time to make, as a temporary solution you can try reverting to 1.18.13 or temporarily hosting your world on Windows machine.

**Comment by Ridderrasmus** [comment]
New release should ideally have a patchwork solution

**Comment by Dmitry221060** [comment]
If you are still encountering this problem - comment here and we will reopen the issue

**Comment by Novabella** [comment]
Just started getting this issue after updating to 1.19.4. That was the only change to the server.

**Comment by TheTechmage** [comment]
Just a heads up, I do appear to be running into this issue with a Linux server for the past two versions. Upon connecting, my client crashes with the following:
```
Running on 64 bit Windows 10.0.19045.0 with 130994 MB RAM
Game Version: v1.20.7 (Stable)
3/29/2025 10:28:03 AM: Critical error occurred
Loaded Mods: barkbeetle@1.0.3, combatoverhaul@0.2.8, doublebackpackcapacity@0.0.1, expandedmolds@1.1.2, immersivecorpsedrop@1.0.3, immersiveorecrush@2.2.1, increasedstoragecapacity@0.0.3, manualdough@1.1.3, manualquenching@1.0.4, manualscraping@1.2.1, millwright@1.1.8, sticksfromfirelogs@1.3.0, game@1.20.7, vsimgui@1.1.7, apeflowerpots@1.2.3, armory@0.2.3, betterfirepit@1.1.5, butchering@1.8.1, carryon@1.8.0-rc.4, combat-overhaul-reanimated@1.0.0, commonlib@2.6.1, configlib@1.5.2, coreofarts@0.2.3, customtransitionlib@1.0.0, desertificationsurfacevariation@1.0.0, fieldsofsalt@1.2.2, foodshelves@1.5.3, fromgoldencombs@1.8.12, hardcorewater@1.3.5, immersivewoodsawing@0.2.7, livemap@0.0.9, maltiezcrossbows@1.0.0, maltiezfirearms@0.11.2, mannequinstand@1.0.5, oneroof@1.8.2, postsandbeams@1.4.0, rpvoicechat@2.3.16, simplefootstepsredux@1.0.1, smithingplus@1.4.1, trailmodcupdate@1.2.1, creative@1.20.7, survival@1.20.7, artofcooking@0.2.4, artofgrowing@0.5.3, autoconfiglib@2.0.4, brainfreeze@1.1.1, campaigncartographer@4.6.7, em@3.2.1, playercorpse@1.11.0, shearlib@1.1.2, stonequarry@3.4.3, tailorsdelight@1.9.4, wool@1.6.1, dressmakers@1.5.2
System.Exception: Don't know how to instantiate item of class 'soundemittingitem' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 332
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 196
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 606
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 424
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 377
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Event Log entries for Vintagestory.exe, the latest 2
==================================
{ TimeGenerated = 3/29/2025 10:16:39 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.7.0, time stamp: 0x66470000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5607, time stamp: 0x18768d24
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x13964
Faulting application start time: 0x01dba0cd9415e1f9
Faulting application path: S:\Users\Frosty\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 693f3274-2c8a-4af0-86e6-1744e1ddbdea
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 3/29/2025 10:11:12 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.20.7.0, time stamp: 0x66470000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5607, time stamp: 0x18768d24
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x10370
Faulting application start time: 0x01dba0ccae3d14fd
Faulting application path: S:\Users\Frosty\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 35e3e167-54d5-4977-b7ef-d179e2109887
Faulting package full name: 
Faulting package-relative application ID:  }
```

Removing RPVoiceChat stops VS from crashing.
